const carBrands: string[] = [
    "Audi",
    "BMW",
    "Ford",
    "Geely",
    "Haval",
    "Honda",
    "Hyundai",
    "Kia",
    "Lada",
    "Mazda",
    "Mercedes-Benz",
    "Mitsubishi",
    "Nissan",
    "Renault",
    "Skoda",
    "Toyota",
    "Volkswagen",
    "Acura",
    "Daihatsu",
    "Datsun",
    "Infiniti",
    "Isuzu",
    "Lexus",
    "Subaru",
    "Suzuki",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Dodge",
    "GMC",
    "Hummer",
    "Jeep",
    "Lincoln",
    "Mercury",
    "Oldsmobile",
    "Pontiac",
    "Tesla",
    "Aurus",
    "GAZ",
    "Moskvich",
    "TagAZ",
    "UAZ",
    "Alfa Romeo",
    "Aston Martin",
    "Bentley",
    "Bugatti",
    "Citroen",
    "DS",
    "Ferrari",
    "Fiat",
    "Jaguar",
    "Lamborghini",
    "Lancia",
    "Land Rover",
    "Maserati",
    "Maybach",
    "Mini",
    "Peugeot",
    "Ravon",
    "Rolls-Royce",
    "Rover",
    "Saab",
    "SEAT",
    "Smart",
    "Volvo",
    "ZAZ",
    "Brilliance",
    "BYD",
    "Changan",
    "Chery",
    "DongFeng",
    "Exeed",
    "FAW",
    "Foton",
    "GAC",
    "Great Wall",
    "Haima",
    "JAC",
    "Kaiyi",
    "Lifan",
    "Luxgen",
    "Omoda",
    "Tank",
    "Zotye",
    "AC Cars",
    "Alpina",
    "Asia Motors",
    "BIOAUTO",
    "Changfeng",
    "Changhe",
    "Dacia",
    "Dadi",
    "Daewoo",
    "Derways",
    "FAW",
    "Hafei Motor",
    "Iran Khodro",
    "JAC",
    "MG",
    "MINI",
    "Proton",
    "Tata",
    "Tatra",
    "Yamaha",
];

const carModels: string[] = [
    "Camry",
    "Civic",
    "Accord",
    "Mustang",
    "Corolla",
    "Charger",
    "Model S",
    "CX-5",
    "Qashqai",
    "Octavia",
    "Astra",
    "Golf",
    "Focus",
    "Fiesta",
    "Cruze",
    "Impala",
    "Malibu",
    "Fusion",
    "Escape",
    "Explorer",
    "Pilot",
    "Elantra",
    "Sonata",
    "Tucson",
    "Santa Fe",
    "Optima",
    "Sorento",
    "Sportage",
    "Soul",
    "Forte",
    "Rio",
    "Stinger",
    "Telluride",
    "Cherokee",
    "Grand Cherokee",
    "Wrangler",
    "Compass",
    "Renegade",
    "Pacifica",
    "300",
    "Ram 1500",
    "Silverado 1500",
    "F-150",
    "Ranger",
    "Tacoma",
    "Tundra",
    "Highlander",
    "RAV4",
    "CR-V",
    "Pilot",
    "X5",
    "3 Series",
    "A4",
    "Q7",
    "911",
    "Cayenne",
    "Spider",
    "Giulia",
    "Chiron",
    "Veyron",
    "Continental GT",
    "Flying Spur",
    "Defender",
    "Discovery",
    "Range Rover",
    "Velar",
    "Evoque",
    "F-Type",
    "XE",
    "XF",
    "XJ",
    "C-Class",
    "E-Class",
    "S-Class",
    "GLE",
    "GLC",
    "A-Class",
    "B-Class",
    "CLA",
    "CLS",
    "Cooper",
    "Countryman",
    "Clubman",
    "Paceman",
    "Roadster",
    "GranTurismo",
    "Levante",
    "Ghibli",
    "Quattroporte",
    "GranCabrio",
    "Ghost",
    "Phantom",
    "Wraith",
    "Dawn",
    "Cullinan",
    "Model X",
    "Model 3",
    "Model Y",
    "Roadster",
    "Cybertruck",
    "Leaf",
    "Juke",
    "GT-R",
    "370Z",
    "Murano",
    "Pathfinder",
    "Armada",
    "Rogue",
    "Sentra",
    "Altima",
];

export const getRandomCarName = (): string =>
    `${carBrands[Math.round(Math.random() * (carBrands.length - 1))]} ${carModels[Math.round(Math.random() * (carModels.length - 1))]}`;

export const getRandomCarColor = (): string => {
    const Maxcolorvalue = 255;
    const numRed = Math.round(Math.random() * Maxcolorvalue).toString(16);
    const numGreen = Math.round(Math.random() * Maxcolorvalue).toString(16);
    const numBlue = Math.round(Math.random() * Maxcolorvalue).toString(16);
    return `#${numRed}${numGreen}${numBlue}`;
};
